return {
"kilobit",
"3024 Day",
"3024 Night",
"Adventure",
"AdventureTime",
"Afterglow",
"Alabaster",
"AlienBlood",
"Andromeda",
"Apprentice (base16)",
"Argonaut",
"Arthur",
"Ashes (base16)",
"Atom",
"AtomOneLight",
"Aurora",
"ayu",
"Ayu Mirage",
"ayu_light",
"Bamboo",
"Bamboo Light",
"Banana Blueberry",
"Batman",
"Belafonte Day",
"Belafonte Night",
"BirdsOfParadise",
"Blazer",
"BlueBerryPie",
"BlulocoDark",
"BlulocoLight",
"Borland",
"Breeze",
"Bright Lights",
"Broadcast",
"Brogrammer",
"Builtin Dark",
"Builtin Light",
"Builtin Pastel Dark",
"Builtin Solarized Dark",
"Builtin Solarized Light",
"Builtin Tango Dark",
"Builtin Tango Light",
"Calamity",
"carbonfox",
"Catppuccin Frappe",
"Catppuccin Latte",
"Catppuccin Macchiato",
"Catppuccin Mocha",
"ChallengerDeep",
"Cobalt Neon",
"Cobalt2",
"coffee_theme",
"CutiePro",
"Cyberdyne",
"cyberpunk",
"Dark Pastel",
"Dark+",
"darkermatrix",
"darkmatrix",
"Darkside",
"deep",
"Desert",
"DimmedMonokai",
"Django",
"DjangoRebornAgain",
"DjangoSmooth",
"Doom Peacock",
"DoomOne",
"Dracula",
"Dracula (Official)",
"Dracula+",
"duckbones",
"Duotone Dark",
"duskfox",
"Earthsong",
"Eldritch",
"Elemental",
"Elementary",
"ENCOM",
"Espresso",
"Espresso Libre",
"Everblush",
"Fahrenheit",
"Fairyfloss",
"farmhouse-dark",
"farmhouse-light",
"Fideloper",
"Firefly Traditional",
"FirefoxDev",
"Firewatch",
"FishTank",
"Flat",
"Flatland",
"flexoki-dark",
"flexoki-light",
"Floraverse",
"ForestBlue",
"Framer",
"FrontEndDelight",
"FunForrest",
"Galaxy",
"Galizur",
"Github",
"GitHub Dark",
"Glacier",
"Grape",
"Grass",
"Grey-green",
"GruvboxDark",
"GruvboxDarkHard",
"GruvboxLight",
"Guezwhoz",
"Hacktober",
"Hardcore",
"hardhacker",
"Harper",
"HaX0R_BLUE",
"HaX0R_GR33N",
"HaX0R_R3D",
"Highway",
"Hipster Green",
"Hivacruz",
"Homebrew",
"Hopscotch",
"Hybrid",
"IC_Green_PPL",
"IC_Orange_PPL",
"iceberg-dark",
"iceberg-light",
"idea",
"idleToes",
"IR_Black",
"iTerm2 Dark Background",
"iTerm2 Default",
"iTerm2 Light Background",
"iTerm2 Smoooooth",
"iTerm2 Tango Dark",
"iTerm2 Tango Light",
"Jackie Brown",
"Japanesque",
"Jellybeans",
"JetBrains Darcula",
"jubi",
"kanagawabones",
"Kibble",
"Kolorit",
"Konsolas",
"kurokula",
"Lab Fox",
"Laser",
"Later This Evening",
"Lavandula",
"LiquidCarbon",
"LiquidCarbonTransparent",
"lovelace",
"Mariana",
"Material",
"MaterialDark",
"MaterialDarker",
"MaterialDesignColors",
"MaterialOcean",
"Mathias",
"matrix",
"Medallion",
"Mellifluous",
"midnight-in-mojave",
"Mirage",
"Misterioso",
"Modus-Operandi",
"Modus-Vivendi",
"Molokai",
"MonaLisa",
"Monokai Remastered",
"Monokai Soda",
"Monokai Vivid",
"N0tch2k",
"Neon",
"Neopolitan",
"Neutron",
"Night Owlish Light",
"nightfox",
"NightLion v1",
"NightLion v2",
"niji",
"Nocturnal Winter",
"nord",
"nord-light",
"nordfox",
"Novel",
"NvimDark",
"NvimLight",
"Obsidian",
"Ocean",
"Oceanic-Next",
"OceanicMaterial",
"Ollie",
"OneHalfDark",
"OneHalfLight",
"Operator Mono Dark",
"Overnight Slumber",
"PaleNightHC",
"Pandora",
"Paraiso Dark",
"PaulMillr",
"PencilDark",
"PencilLight",
"Peppermint",
"Piatto Light",
"Pnevma",
"Poimandres",
"Poimandres Storm",
"Popping and Locking",
"primary",
"Pro",
"Pro Light",
"Purple Rain",
"purplepeter",
"Rapture",
"Raycast_Dark",
"Raycast_Light",
"rebecca",
"Red Alert",
"Red Planet",
"Red Sands",
"Relaxed",
"Retro",
"Rippedcasts",
"rose-pine",
"rose-pine-dawn",
"rose-pine-moon",
"Rouge 2",
"Royal",
"Ryuuko",
"Sakura",
"Scarlet Protocol",
"Seafoam Pastel",
"SeaShells",
"Sequoia Monochrome",
"Sequoia Moonlight",
"Seti",
"shades-of-purple",
"Shaman",
"Slate",
"SleepyHollow",
"Smyck",
"Snazzy",
"SoftServer",
"Solarized Darcula",
"Solarized Dark - Patched",
"Solarized Dark Higher Contrast",
"SpaceGray",
"SpaceGray Eighties",
"SpaceGray Eighties Dull",
"Spacedust",
"Spiderman",
"Spring",
"Square",
"Sublette",
"Subliminal",
"Sugarplum",
"Sundried",
"Symfonic",
"synthwave",
"synthwave-everything",
"SynthwaveAlpha",
"Tango Adapted",
"Tango Half Adapted",
"Teerb",
"Terminal Basic",
"Thayer Bright",
"The Hulk",
"Tinacious Design (Dark)",
"Tinacious Design (Light)",
"Tokyo Night",
"Tokyo Night Day",
"Tokyo Night Moon",
"Tokyo Night Storm",
"tokyonight",
"tokyonight-day",
"tokyonight-storm",
"Tomorrow",
"Tomorrow Night",
"Tomorrow Night Blue",
"Tomorrow Night Bright",
"Tomorrow Night Burns",
"Tomorrow Night Eighties",
"ToyChest",
"Treehouse",
"Twilight",
"Ubuntu",
"UltraDark",
"UltraViolent",
"UnderTheSea",
"Unikitty",
"Urple",
"Vaughn",
"Vesper",
"VibrantInk",
"Violet Dark",
"Violet Light",
"Warm Neon",
"WarmNeon",
"Wez",
"Whimsy",
"WildCherry",
"wilmersdorf",
"Wombat",
"Wryan",
"zenbones",
"zenbones_dark",
"Zenburn",
"zenburned",
"zenwritten_dark",
"zenwritten_light",
}
